### ISSUE TITLE
Won't install 

### ISSUE THREAD

**Issue by mwaqar99** [muschellij2/dcmsort#2]
Hi there, 
I am trying to install dcmsort with R 4.0.5 and get the following error: 

Downloading GitHub repo muschellij2/dcmsort@HEAD
Downloading GitHub repo jonclayden/tractor@HEAD
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/jonclayden/reportr.git /var/folders/tf/352yhl0x683dznqzbdnh0zv40000gp/T//RtmpAJKro8/remotes24177ffa62c2/tractor-tractor-c270ecf/tractor.base/../lib/reportr
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failed to install 'dcmsort' from GitHub:
  Failed to install 'tractor.base' from GitHub:
  Command failed (1)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/jonclayden/reportr.git /var/folders/tf/352yhl0x683dznqzbdnh0zv40000gp/T//RtmpAJKro8/remotes24177ffa62c2/tractor-tractor-c270ecf/tractor.base/../lib/reportr' had status 1

Any solution?

**Comment by muschellij2** [comment]
It seems like an issue for https://github.com/jonclayden/reportr

**Comment by mwaqar99** [comment]
Temporary solution is:
1) It needed the dependency tractor.base
2) For some reason still wouldn't install with the direct link, so had to install the tar.gz file from terminal
